### ISSUE TITLE
Store settings in a configuration file

### ISSUE THREAD

**Issue by ageorgou** [oracc/oracc-search-front-end#15]
From comments on #12, #13. This could include, among others:

- The URL (host and port) of the backend server
- The URL of p3, or whatever replaces it, that clicked entries should lead to

**Comment by tim-band** [comment]
This has been added in commit [f555eb2](https://github.com/oracc/oracc-search-front-end/commit/f555eb2ee034f28fa165e944da8a9481b302ea71)
I don't think it was added in a PR; at least github isn't showing me one.
