### ISSUE TITLE
Fix text in Help section

### ISSUE THREAD

**Issue by raquelalegre** [oracc/oracc-search-front-end#18]
- [ ] "click here" is not clickable
- [x] Rephrase "include" bit
- [x] Don't use "query" twice - or it may be "query" is not the word to use here

**Comment by raquel-ucl** [comment]
This is needed before the next user test.

**Comment by ageorgou** [comment]
Arabic (Google) translations still need to be updated!

Making the text clickable is more tricky than expected, from what I remember of previous attempts, but I will look into it.

**Comment by tim-band** [comment]
This is obsolete.
