### ISSUE TITLE
Decide what to do with the two tables

### ISSUE THREAD

**Issue by ageorgou** [oracc/oracc-search-front-end#22]
There are currently two ways of seeing the results, accessible through the Search and Browse tabs.  These correspond to `DisplayTableComponent` and `SearchTableComponent`, respectfully. These classes do not share code, which is a little annoying for now, but could become more problematic. We should either:

- Decide to do away with the Browse option, which takes a long time to load
- Refactor some of the code so that they share a base class with common functionality (see also 187f51bed5ad9f84d494090243953fe568c0e01b)

(or some other solution)

**Comment by tim-band** [comment]
We no longer have Search and Browse tabs
