### ISSUE TITLE
Access individual text by URL

### ISSUE THREAD

**Issue by ageorgou** [oracc/oracc-search-front-end#31]
In the old website, [a text can be accessed by a URL](http://oracc.museum.upenn.edu/doc/help/visitingoracc/citingurls/index.html) of the form  `http://oracc.museum.upenn.edu/project[/subproject]/text_id/html` ([example](http://oracc.museum.upenn.edu/cams/gkab/P363523/html)).
We should add this functionality for the new website, instead of having the search as the only frontend.
Also related to #29.

**Comment by jhughes982** [comment]
Thanks for the clarifications! Another quick question:
- Are project texts always found under the format `http://oracc.museum.upenn.edu/project[/subproject]/text_id/html`. Or could a text also exist under `http://oracc.museum.upenn.edu/project/text_id/html` (i.e. without a subproject?)

**Comment by ageorgou** [comment]
That's also possible, the subproject part is optional (that's what I tried to convey with the `[...]`!)

For example:
- (no subproject) http://oracc.museum.upenn.edu/dsst/Q000771/html
- (project + subproject) http://oracc.museum.upenn.edu/adsd/adart2/X201642/html

**Comment by jhughes982** [comment]
For reference:
- Link to a text on the old website with the right formatting: http://oracc.museum.upenn.edu/dcclt/P322250/
- It looks like Angular might be pulling data from these URL's via a link that is dynamically generated

**Comment by ageorgou** [comment]
Implemented in #35, now works on the server too (e.g. https://build-oracc.museum.upenn.edu/new/dcclt/P322250)
